/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BodyView: typeof import('./src/components/BodyView/index.vue')['default']
    ButtonsView: typeof import('./src/components/ButtonsView/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElRow: typeof import('element-plus/es')['ElRow']
    GlobalPoseView: typeof import('./src/components/GlobalPoseView/index.vue')['default']
    ModelView: typeof import('./src/components/ModelView/index.vue')['default']
    OperationView: typeof import('./src/components/OperationView/index.vue')['default']
    TopView: typeof import('./src/components/TopView/index.vue')['default']
  }
}
