/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddView: typeof import('./src/components/AddView/index.vue')['default']
    BannerView: typeof import('./src/components/BannerView/index.vue')['default']
    BodyView: typeof import('./src/components/BodyView/index.vue')['default']
    ButtonsView: typeof import('./src/components/ButtonsView/index.vue')['default']
    ContentMenu: typeof import('./src/components/ContentMenu/index.vue')['default']
    DropDownMenu: typeof import('./src/components/DropDownMenu/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    GlobalPoseView: typeof import('./src/components/GlobalPoseView/index.vue')['default']
    ModelView: typeof import('./src/components/ModelView/index.vue')['default']
    OperationView: typeof import('./src/components/OperationView/index.vue')['default']
    PoseListView: typeof import('./src/components/PoseListView/index.vue')['default']
    RenderModalView: typeof import('./src/components/RenderModalView/index.vue')['default']
    SafeArea: typeof import('./src/components/DropDownMenu/safeArea.vue')['default']
    TopView: typeof import('./src/components/TopView/index.vue')['default']
  }
}
