/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BodyView: typeof import('./src/components/BodyView/index.vue')['default']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ModelView: typeof import('./src/components/ModelView/index.vue')['default']
    TopView: typeof import('./src/components/TopView/index.vue')['default']
  }
}
